In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("..")

from datasets.img_dataset import FoodImgs
from models.cnn import SnapSnack

In [2]:
import pytorch_lightning as pl
from torch.utils.data import DataLoader, random_split
import math


dataset = FoodImgs()

s = len(dataset)
print(f"{s} imgs")
train_size = int(math.ceil(s * 0.8))
test_size = s - train_size

train_set, test_set = random_split(dataset, [train_size, test_size])


9090 imgs


In [3]:
import torch
model = SnapSnack(output_dim=4)
model.load_state_dict(torch.load("../models/model_2.pt"))

<All keys matched successfully>

In [4]:
model = model.cpu().eval()

In [5]:
preds = []
targets = []
with torch.no_grad():
    for img, target in DataLoader(test_set, batch_size=1):
        pred = model(img)
        preds.append(pred)
        targets.append(target)

In [7]:
preds[:10], targets[:10]

([tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]]),
  tensor([[-0.0787, -0.0211,  0.1330,  0.0795]])],
 [tensor([[-0.0159, -0.0206, -0.0153, -0.0152]]),
  tensor([[-0.0175, -0.0258, -0.0169, -0.0178]]),
  tensor([[-0.0170, -0.0256, -0.0166, -0.0187]]),
  tensor([[-0.0144, -0.0040, -0.0136, -0.0166]]),
  tensor([[-0.0163, -0.0193, -0.0156, -0.0155]]),
  tensor([[-0.0170, -0.0256, -0.0162, -0.0185]]),
  tensor([[-0.0170, -0.0175, -0.0164, -0.0184]]),
  tensor([[-0.0169, -0.0256, -0.0169, -0.0174]]),
  tensor([[-0.0168, -0.0238, -0.0166, -0.0164]]),
  tensor([[-0.0160, -0.0243, -0.0152, -0.0178]])]

In [10]:
preds = torch.cat(preds)

In [12]:
preds[:,0]

tensor([-0.0787, -0.0787, -0.0787,  ..., -0.0787, -0.0787, -0.0787])

In [13]:
targets = torch.cat(targets)

In [14]:
targets[:, 0]

tensor([-0.0159, -0.0175, -0.0170,  ..., -0.0168, -0.0166, -0.0175])