In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("..")

from datasets.img_dataset import FoodImgs
from models.cnn import SnapSnack

In [13]:
import pytorch_lightning as pl
from torch.utils.data import DataLoader, random_split
import math
from torchvision import transforms as T

transforms = T.Compose(
                [
                    T.Resize(256),
                    T.CenterCrop(224),
                    T.ToTensor(),
                    T.Normalize(
                        mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
                    ),
                ]
            )

dataset = FoodImgs(
    transforms = transforms,
)

s = len(dataset)
train_size = int(math.ceil(s * 0.7))
test_size = int(math.ceil(s * 0.15))
val_size = s - test_size - train_size

train_set, val_set, test_set = random_split(dataset, [train_size, val_size, test_size])
print(f"{len(train_set)} train imgs \n{len(val_set)} val imgs\n{len(test_set)} test imgs")

6363 train imgs 
1363 val imgs
1364 test imgs


In [14]:
from pytorch_lightning.loggers import WandbLogger
import wandb
# wandb.init(project="snapnsnack")
wandb_logger = WandbLogger(project='snapnsnack')
model = SnapSnack(fc_layers=(), output_dim=4, lr=1)
trainer = pl.Trainer(logger=wandb_logger, max_epochs=5)
trainer.fit(model, train_dataloader=DataLoader(train_set, batch_size=3), val_dataloaders=DataLoader(val_set), )

GPU available: False, used: False
TPU available: False, using: 0 TPU cores


wandb: wandb version 0.10.12 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade



  | Name     | Type      | Params
---------------------------------------
0 | backbone | ResNet    | 11 M  
1 | softmax  | Softmax   | 0     
2 | loss     | KLDivLoss | 0     
/opt/anaconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


tensor([176.,   5.,   7.,  41.])
tensor([1552.,   60.,  106., 3916.])
tensor([153.,   5.,  10.,  53.])


/opt/anaconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The validation_epoch_end should not return anything as of 9.1.to log, use self.log(...) or self.write(...) directly in the LightningModule
  warnings.warn(*args, **kwargs)
/opt/anaconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


tensor([ 51.,   1.,   3., 107.])
tensor([88.,  0.,  9.,  0.])
tensor([282.,   4.,  14.,  15.])
tensor([202.,   7.,  10.,  52.])
tensor([270.,   4.,   0.,  57.])
tensor([713.,  60.,  51., 971.])
tensor([[0.1100, 0.1425, 0.4116, 0.3360],
        [0.1366, 0.1927, 0.3242, 0.3464],
        [0.1427, 0.1867, 0.3309, 0.3397]], grad_fn=<SoftmaxBackward>)
tensor([[0.3148, 0.0062, 0.0185, 0.6605],
        [0.9072, 0.0000, 0.0928, 0.0000],
        [0.8952, 0.0127, 0.0444, 0.0476]])
1.2430739402770996
tensor([167.,   3.,   7.,  97.])
tensor([194.,   2.,   3., 697.])
tensor([906.,  57.,  53., 284.])
tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]], grad_fn=<SoftmaxBackward>)
tensor([[0.7454, 0.0258, 0.0369, 0.1919],
        [0.8157, 0.0121, 0.0000, 0.1722],
        [0.3972, 0.0334, 0.0284, 0.5409]])
4.8672332763671875
tensor([940., 100.,  38., 800.])
tensor([168.,  14.,  10., 460.])
tensor([336.,  44.,  16., 413.])
tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
    

/opt/anaconda3/envs/py36/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  warnings.warn(*args, **kwargs)


1

In [25]:
import torch
import pickle as pkl
import pandas as pd
epi = pd.read_csv("../data/snapnsnackdb/epi_r.csv")

epi.head()

title  rating  calories  protein  \
0              Lentil, Apple, and Turkey Wrap    2.500     426.0     30.0   
1  Boudin Blanc Terrine with Red Onion Confit    4.375     403.0     18.0   
2                Potato and Fennel Soup Hodge    3.750     165.0      6.0   
3             Mahi-Mahi in Tomato Olive Sauce    5.000       NaN      NaN   
4                    Spinach Noodle Casserole    3.125     547.0     20.0   

    fat  sodium  #cakeweek  #wasteless  22-minute meals  3-ingredient recipes  \
0   7.0   559.0        0.0         0.0              0.0                   0.0   
1  23.0  1439.0        0.0         0.0              0.0                   0.0   
2   7.0   165.0        0.0         0.0              0.0                   0.0   
3   NaN     NaN        0.0         0.0              0.0                   0.0   
4  32.0   452.0        0.0         0.0              0.0                   0.0   

   ...  yellow squash  yogurt  yonkers  yuca  zucchini  cookbooks  leftovers  \
0  ...            0.0     0.0      0.0   0.0       0.0        0.0        0.0   
1  ...            0.0     0.0      0.0   0.0       0.0        0.0        0.0   
2  ...            0.0     0.0      0.0   0.0       0.0        0.0        0.0   
3  ...            0.0     0.0      0.0   0.0       0.0        0.0        0.0   
4  ...            0.0     0.0      0.0   0.0       0.0        0.0        0.0   

   snack  snack week  turkey  
0    0.0         0.0     1.0  
1    0.0         0.0     0.0  
2    0.0         0.0     0.0  
3    0.0         0.0     0.0  
4    0.0         0.0     0.0  

[5 rows x 680 columns]

In [30]:
img_4 = "/Users/davinan/Dropbox/github/Snap-N-Snack/data/snapnsnackdb/simple_images/Spinach+Noodle+Casserole+/Spinach+Noodle+Casserole+_1.jpeg"

In [35]:
import matplotlib.pyplot as plt
im = plt.imread(img_4)

In [43]:
from torchvision import transforms as T
from PIL import Image

transform = T.Compose(
            [
                T.ToTensor(),
                T.Normalize(
                    mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
                ),
                T.Resize(256),
                T.CenterCrop(224),
            ]
        )

model.eval()
oi = transform(Image.fromarray(im)).unsqueeze(0)
preds = model(oi)

In [44]:
preds

tensor([[  3.7612, 327.7388,  11.6335,  22.7230, 274.9613]],
       grad_fn=<AddmmBackward>)

In [5]:
import torch
torch.__version__

'1.7.0'

In [10]:
import torchvision
torchvision.__version__

'0.8.1'

In [35]:
epi = epi.dropna()
epi

title  rating  calories  protein  \
0                  Lentil, Apple, and Turkey Wrap    2.500     426.0     30.0   
1      Boudin Blanc Terrine with Red Onion Confit    4.375     403.0     18.0   
2                    Potato and Fennel Soup Hodge    3.750     165.0      6.0   
4                        Spinach Noodle Casserole    3.125     547.0     20.0   
5                                   The Best Blts    4.375     948.0     19.0   
...                                            ...     ...       ...      ...   
20047                              Parmesan Puffs    3.125      28.0      2.0   
20048              Artichoke and Parmesan Risotto    4.375     671.0     22.0   
20049                       Turkey Cream Puff Pie    4.375     563.0     31.0   
20050     Snapper on Angel Hair with Citrus Cream    4.375     631.0     45.0   
20051  Baked Ham with Marmalade-Horseradish Glaze    4.375     560.0     73.0   

        fat  sodium  #cakeweek  #wasteless  22-minute meals  \
0       7.0   559.0        0.0         0.0              0.0   
1      23.0  1439.0        0.0         0.0              0.0   
2       7.0   165.0        0.0         0.0              0.0   
4      32.0   452.0        0.0         0.0              0.0   
5      79.0  1042.0        0.0         0.0              0.0   
...     ...     ...        ...         ...              ...   
20047   2.0    64.0        0.0         0.0              0.0   
20048  28.0   583.0        0.0         0.0              0.0   
20049  38.0   652.0        0.0         0.0              0.0   
20050  24.0   517.0        0.0         0.0              0.0   
20051  10.0  3698.0        0.0         0.0              0.0   

       3-ingredient recipes  ...  yellow squash  yogurt  yonkers  yuca  \
0                       0.0  ...            0.0     0.0      0.0   0.0   
1                       0.0  ...            0.0     0.0      0.0   0.0   
2                       0.0  ...            0.0     0.0      0.0   0.0   
4                       0.0  ...            0.0     0.0      0.0   0.0   
5                       0.0  ...            0.0     0.0      0.0   0.0   
...                     ...  ...            ...     ...      ...   ...   
20047                   0.0  ...            0.0     0.0      0.0   0.0   
20048                   0.0  ...            0.0     0.0      0.0   0.0   
20049                   0.0  ...            0.0     0.0      0.0   0.0   
20050                   0.0  ...            0.0     0.0      0.0   0.0   
20051                   0.0  ...            0.0     0.0      0.0   0.0   

       zucchini  cookbooks  leftovers  snack  snack week  turkey  
0           0.0        0.0        0.0    0.0         0.0     1.0  
1           0.0        0.0        0.0    0.0         0.0     0.0  
2           0.0        0.0        0.0    0.0         0.0     0.0  
4           0.0        0.0        0.0    0.0         0.0     0.0  
5           0.0        0.0        0.0    0.0         0.0     0.0  
...         ...        ...        ...    ...         ...     ...  
20047       0.0        0.0        0.0    0.0         0.0     0.0  
20048       0.0        0.0        0.0    0.0         0.0     0.0  
20049       0.0        0.0        0.0    0.0         0.0     1.0  
20050       0.0        0.0        0.0    0.0         0.0     0.0  
20051       0.0        0.0        0.0    0.0         0.0     0.0  

[15864 rows x 680 columns]

In [27]:
epi.std()

rating             1.285518
calories      359848.417868
protein         3843.462312
fat            20459.329549
sodium        334042.078448
                  ...      
cookbooks          0.011228
leftovers          0.017751
snack              0.036360
snack week         0.028615
turkey             0.144198
Length: 679, dtype: float64

In [28]:
epi.mean()

rating           3.760952
calories      6350.682993
protein        100.324571
fat            346.986826
sodium        6252.742310
                 ...     
cookbooks        0.000126
leftovers        0.000315
snack            0.001324
snack week       0.000819
turkey           0.021243
Length: 679, dtype: float64

In [48]:
train_set[0]

(tensor([[[ 1.4612,  1.4620,  1.4876,  ...,  1.1964,  1.2565,  1.2898],
          [ 1.4604,  1.4612,  1.4630,  ...,  1.2236,  1.2581,  1.2907],
          [ 1.4466,  1.4481,  1.4550,  ...,  1.2609,  1.2956,  1.3032],
          ...,
          [ 1.5514,  1.3198,  1.4637,  ...,  1.7522,  1.7191,  1.7283],
          [ 1.4293,  1.4341,  1.5262,  ...,  1.7638,  1.7646,  1.7371],
          [ 1.3825,  1.4438,  1.5395,  ...,  1.7559,  1.7344,  1.6855]],
 
         [[ 1.6758,  1.6766,  1.7028,  ...,  1.4082,  1.4665,  1.5006],
          [ 1.6749,  1.6758,  1.6777,  ...,  1.4329,  1.4681,  1.5015],
          [ 1.6609,  1.6624,  1.6695,  ...,  1.4710,  1.5065,  1.5143],
          ...,
          [-0.2446, -0.2617, -0.2779,  ..., -0.2630, -0.2951, -0.2858],
          [-0.3710, -0.3652, -0.3236,  ..., -0.2629, -0.3425, -0.3705],
          [-0.4187, -0.3553, -0.3099,  ..., -0.2710, -0.3734, -0.4234]],
 
         [[ 1.9777,  1.9785,  2.0046,  ...,  1.7101,  1.7694,  1.8033],
          [ 1.9769,  1.9777,

In [60]:
torch.nn.Softmax(dim=1)(torch.tensor([[-10., 10.], [1., 1.]]))

tensor([[2.0612e-09, 1.0000e+00],
        [5.0000e-01, 5.0000e-01]])

In [8]:
import ignite

ModuleNotFoundError: No module named 'ignite'

In [25]:
from torchvision.models import resnet18, resnet50

oi = resnet18()

In [27]:
oi

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  